/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserprofileImport } from './routes/userprofile'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'

// Create/Update Routes

const UserprofileRoute = UserprofileImport.update({
  path: '/userprofile',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/userprofile': {
      id: '/userprofile'
      path: '/userprofile'
      fullPath: '/userprofile'
      preLoaderRoute: typeof UserprofileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/userprofile': typeof UserprofileRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/userprofile': typeof UserprofileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/userprofile': typeof UserprofileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/signup' | '/userprofile'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/userprofile'
  id: '__root__' | '/login' | '/signup' | '/userprofile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UserprofileRoute: typeof UserprofileRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UserprofileRoute: UserprofileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/signup",
        "/userprofile"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/userprofile": {
      "filePath": "userprofile.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
